# Dockerfile
FROM python:3.11

# Tạo thư mục làm việc
WORKDIR /app

# Copy file cấu hình
COPY requirements.txt /app/requirements.txt

# Cài đặt thư viện
RUN pip install --no-cache-dir -r /app/requirements.txt

# Expose cổng API
EXPOSE 8001

# Lệnh khởi động FastAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
