# Generated by Django 5.2.8 on 2025-11-19 04:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='Họ và Tên')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ liên hệ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'indexes': [models.Index(fields=['phone_number'], name='core_custom_phone_n_b7f97e_idx'), models.Index(fields=['full_name'], name='core_custom_full_na_542aed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False, unique=True, verbose_name='VIN (Số khung)')),
                ('model_code', models.CharField(max_length=50, verbose_name='Mã Model Xe')),
                ('manufacturing_date', models.DateField(verbose_name='Ngày Sản xuất')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Ngày Đăng ký lần đầu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehicles', to='core.customer', verbose_name='Chủ sở hữu')),
            ],
            options={
                'verbose_name': 'Xe',
                'verbose_name_plural': 'Xe',
            },
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date', models.DateTimeField(verbose_name='Ngày thực hiện dịch vụ')),
                ('mileage_km', models.IntegerField(verbose_name='Số kilomet lúc dịch vụ')),
                ('service_type', models.CharField(choices=[('MAINTENANCE', 'Bảo dưỡng định kỳ'), ('WARRANTY_CLAIM', 'Sửa chữa Bảo hành'), ('RECALL', 'Chiến dịch triệu hồi'), ('REPAIR', 'Sửa chữa thông thường')], default='MAINTENANCE', max_length=50, verbose_name='Loại dịch vụ')),
                ('description', models.TextField(verbose_name='Mô tả công việc')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='core.vehicle', verbose_name='Xe được dịch vụ')),
            ],
            options={
                'verbose_name': 'Lịch sử dịch vụ',
                'verbose_name_plural': 'Lịch sử dịch vụ',
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePart',
            fields=[
                ('part_serial_number', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Serial Phụ tùng')),
                ('part_code', models.CharField(max_length=50, verbose_name='Mã loại Phụ tùng')),
                ('install_date', models.DateTimeField(verbose_name='Ngày lắp đặt lên xe')),
                ('is_warranty_eligible', models.BooleanField(default=True, verbose_name='Đủ điều kiện bảo hành')),
                ('replaced_old_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial cũ bị thay thế')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_parts', to='core.vehicle', verbose_name='Xe gắn phụ tùng')),
            ],
            options={
                'verbose_name': 'Phụ tùng Xe',
                'verbose_name_plural': 'Phụ tùng Xe',
                'constraints': [models.UniqueConstraint(fields=('part_serial_number',), name='unique_part_serial')],
            },
        ),
    ]
