# Generated by Django 5.2.8 on 2025-11-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaultData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17)),
                ('faultCode', models.CharField(max_length=50)),
                ('partName', models.CharField(max_length=100)),
                ('dateOccurred', models.DateField()),
                ('claimId', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=100, unique=True)),
                ('modelParameters', models.JSONField(default=dict)),
                ('lastTrainedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecallCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignName', models.CharField(max_length=200)),
                ('campaignCode', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('filterCriteria', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17)),
                ('status', models.CharField(choices=[('NOTIFIED', 'Đã thông báo'), ('SCHEDULED', 'Đã đặt lịch'), ('IN_PROGRESS', 'Đang xử lý'), ('COMPLETED', 'Đã hoàn thành')], default='NOTIFIED', max_length=20)),
                ('dateCompleted', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_involved', to='campaigns.recallcampaign')),
            ],
        ),
    ]
